using RetroFun.Controls;
using Geode.Network;

namespace RetroFun.Subscribers
{
    public class ObservablePage : PageUtils
    {
        //Outgoing events shared by multiple pages
        public virtual void Out_RequestRoomHeightmap(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestRoomData(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestRoomCategories(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestResolution(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestReportUserBullying(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestReportRoom(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestRecylerLogic(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestPublicRooms(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestPromotionRooms(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestPromotedRooms(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestProfileFriends(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestPopularRooms(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestPetTrainingPanel(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestPetInfo(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestPetBreeds(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestRoomLoad(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestRoomRights(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestRoomSettings(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestRoomWordFilter(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomPickupItem(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomMute(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomFavorite(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomBackground(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestWearingBadges(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestUserWardrobe(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestUserTags(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestOwnItems(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestUserProfile(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestUserCredits(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestUserClub(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestUserCitizinShip(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestTargetOffer(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestTalenTrack(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestTags(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestSellItem(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestUserData(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestOwnGuilds(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestOffers(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestNewsList(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestGuildBuy(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestGuideTool(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestGuideAssistance(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestGiftConfiguration(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestGameConfigurations(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestFriends(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestFriendRequest(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestGuildBuyRooms(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestDiscount(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestCredits(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestCreateRoom(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestCraftingRecipesAvailable(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestCraftingRecipes(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestClubGifts(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestCatalogPage(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestCatalogMode(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestDeleteRoom(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomPlaceBuildersClubItem(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestGuildFurniWidget(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestGuildJoin(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestNewNavigatorRooms(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestNewNavigatorData(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestNavigatorSettings(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestMyRooms(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestMeMenuSettings(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestItemInfo(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestInventoryPets(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestGuildInfo(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestInventoryItems(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestInventoryBadges(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestInitFriends(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestHighestScoreRooms(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestHeightmap(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestGuildParts(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestGuildMembers(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestGuildManage(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestInventoryBots(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomPlaceItem(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomPlacePaint(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomRemoveAllRights(DataInterceptedEventArgs e) { }
        public virtual void Out_TradeCancelOfferItem(DataInterceptedEventArgs e) { }
        public virtual void Out_TradeAccept(DataInterceptedEventArgs e) { }
        public virtual void Out_ToggleWallItem(DataInterceptedEventArgs e) { }
        public virtual void Out_ToggleMonsterplantBreedable(DataInterceptedEventArgs e) { }
        public virtual void Out_ToggleHFloorObject(DataInterceptedEventArgs e) { }
        public virtual void Out_TestInventory(DataInterceptedEventArgs e) { }
        public virtual void Out_TakeBackItem(DataInterceptedEventArgs e) { }
        public virtual void Out_TradeClose(DataInterceptedEventArgs e) { }
        public virtual void Out_StalkFriend(DataInterceptedEventArgs e) { }
        public virtual void Out_SetHomeRoom(DataInterceptedEventArgs e) { }
        public virtual void Out_SellItem(DataInterceptedEventArgs e) { }
        public virtual void Out_SearchUser(DataInterceptedEventArgs e) { }
        public virtual void Out_SearchRoomsWithRights(DataInterceptedEventArgs e) { }
        public virtual void Out_SearchRoomsVisited(DataInterceptedEventArgs e) { }
        public virtual void Out_SearchRoomsMyFavorite(DataInterceptedEventArgs e) { }
        public virtual void Out_SearchRoomsInGroup(DataInterceptedEventArgs e) { }
        public virtual void Out_SetStackHelperHeight(DataInterceptedEventArgs e) { }
        public virtual void Out_SearchRoomsFriendsOwn(DataInterceptedEventArgs e) { }
        public virtual void Out_TradeConfirm(DataInterceptedEventArgs e) { }
        public virtual void Out_TradeOfferMultipleItems(DataInterceptedEventArgs e) { }
        public virtual void Out_YoutubeRequestNextVideo(DataInterceptedEventArgs e) { }
        public virtual void Out_WiredTriggerSaveData(DataInterceptedEventArgs e) { }
        public virtual void Out_WiredEffectSaveData(DataInterceptedEventArgs e) { }
        public virtual void Out_WiredConditionSaveData(DataInterceptedEventArgs e) { }
        public virtual void Out_Username(DataInterceptedEventArgs e) { }
        public virtual void Out_UserWearBadge(DataInterceptedEventArgs e) { }
        public virtual void Out_UserSaveLook(DataInterceptedEventArgs e) { }
        public virtual void Out_TradeOfferItem(DataInterceptedEventArgs e) { }
        public virtual void Out_UserNux(DataInterceptedEventArgs e) { }
        public virtual void Out_UnbanRoomUser(DataInterceptedEventArgs e) { }
        public virtual void Out_UnIgnoreRoomUser(DataInterceptedEventArgs e) { }
        public virtual void Out_TriggerOneWayGate(DataInterceptedEventArgs e) { }
        public virtual void Out_TriggerDice(DataInterceptedEventArgs e) { }
        public virtual void Out_TriggerColorWheel(DataInterceptedEventArgs e) { }
        public virtual void Out_TradeUnAccept(DataInterceptedEventArgs e) { }
        public virtual void Out_TradeStart(DataInterceptedEventArgs e) { }
        public virtual void Out_UserActivity(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestCatalogIndex(DataInterceptedEventArgs e) { }
        public virtual void Out_SearchRoomsFriendsNow(DataInterceptedEventArgs e) { }
        public virtual void Out_SearchRooms(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserShout(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserRemoveRights(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserMute(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserLookAtPoint(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserKick(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserGiveRights(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserGiveRespect(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserSign(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserGiveHandItem(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserDance(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserBan(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserAction(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomStaffPick(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomSettingsSave(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomRequestBannedUsers(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomRemoveRights(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserDropHandItem(DataInterceptedEventArgs e) { }
        public virtual void Out_SearchRoomsByTag(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserSit(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserStopTyping(DataInterceptedEventArgs e) { }
        public virtual void Out_ScratchPet(DataInterceptedEventArgs e) { }
        public virtual void Out_SaveWindowSettings(DataInterceptedEventArgs e) { }
        public virtual void Out_SaveWardrobe(DataInterceptedEventArgs e) { }
        public virtual void Out_SaveUserVolumes(DataInterceptedEventArgs e) { }
        public virtual void Out_SavePreferOldChat(DataInterceptedEventArgs e) { }
        public virtual void Out_SavePostItStickyPole(DataInterceptedEventArgs e) { }
        public virtual void Out_SaveMotto(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserStartTyping(DataInterceptedEventArgs e) { }
        public virtual void Out_SaveIgnoreRoomInvites(DataInterceptedEventArgs e) { }
        public virtual void Out_SSOTicket(DataInterceptedEventArgs e) { }
        public virtual void Out_RotateMoveItem(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomWordFilterModify(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomVote(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserWhisper(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserWalk(DataInterceptedEventArgs e) { }
        public virtual void Out_RoomUserTalk(DataInterceptedEventArgs e) { }
        public virtual void Out_SaveBlockCameraFollow(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestCanCreateRoom(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestCameraConfiguration(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestAchievements(DataInterceptedEventArgs e) { }
        public virtual void Out_GuardianVote(DataInterceptedEventArgs e) { }
        public virtual void Out_GuardianNoUpdatesWanted(DataInterceptedEventArgs e) { }
        public virtual void Out_GuardianAcceptRequest(DataInterceptedEventArgs e) { }
        public virtual void Out_GetPollData(DataInterceptedEventArgs e) { }
        public virtual void Out_GetMarketplaceConfig(DataInterceptedEventArgs e) { }
        public virtual void Out_GetHabboGuildBadgesMessage(DataInterceptedEventArgs e) { }
        public virtual void Out_GetClubData(DataInterceptedEventArgs e) { }
        public virtual void Out_GuideCancelHelpRequest(DataInterceptedEventArgs e) { }
        public virtual void Out_GenerateSecretKey(DataInterceptedEventArgs e) { }
        public virtual void Out_GameCenterRequestAccountStatus(DataInterceptedEventArgs e) { }
        public virtual void Out_GameCenterLoadGame(DataInterceptedEventArgs e) { }
        public virtual void Out_GameCenterJoinGame(DataInterceptedEventArgs e) { }
        public virtual void Out_GameCenter(DataInterceptedEventArgs e) { }
        public virtual void Out_FriendRequest(DataInterceptedEventArgs e) { }
        public virtual void Out_FriendPrivateMessage(DataInterceptedEventArgs e) { }
        public virtual void Out_FootballGateSaveLook(DataInterceptedEventArgs e) { }
        public virtual void Out_GameCenterRequestGameStatus(DataInterceptedEventArgs e) { }
        public virtual void Out_FloorPlanEditorSave(DataInterceptedEventArgs e) { }
        public virtual void Out_GuideCloseHelpRequest(DataInterceptedEventArgs e) { }
        public virtual void Out_GuideInviteUser(DataInterceptedEventArgs e) { }
        public virtual void Out_GuildRemoveMember(DataInterceptedEventArgs e) { }
        public virtual void Out_GuildRemoveFavorite(DataInterceptedEventArgs e) { }
        public virtual void Out_GuildRemoveAdmin(DataInterceptedEventArgs e) { }
        public virtual void Out_GuildDelete(DataInterceptedEventArgs e) { }
        public virtual void Out_GuildDeclineMembership(DataInterceptedEventArgs e) { }
        public virtual void Out_GuildConfirmRemoveMember(DataInterceptedEventArgs e) { }
        public virtual void Out_GuildChangeSettings(DataInterceptedEventArgs e) { }
        public virtual void Out_GuideHandleHelpRequest(DataInterceptedEventArgs e) { }
        public virtual void Out_GuildChangeNameDesc(DataInterceptedEventArgs e) { }
        public virtual void Out_GuildChangeBadge(DataInterceptedEventArgs e) { }
        public virtual void Out_GuildAcceptMembership(DataInterceptedEventArgs e) { }
        public virtual void Out_GuideVisitUser(DataInterceptedEventArgs e) { }
        public virtual void Out_GuideUserTyping(DataInterceptedEventArgs e) { }
        public virtual void Out_GuideUserMessage(DataInterceptedEventArgs e) { }
        public virtual void Out_GuideReportHelper(DataInterceptedEventArgs e) { }
        public virtual void Out_GuideRecommendHelper(DataInterceptedEventArgs e) { }
        public virtual void Out_GuildChangeColors(DataInterceptedEventArgs e) { }
        public virtual void Out_GuildSetAdmin(DataInterceptedEventArgs e) { }
        public virtual void Out_FloorPlanEditorRequestDoorSettings(DataInterceptedEventArgs e) { }
        public virtual void Out_FindNewFriends(DataInterceptedEventArgs e) { }
        public virtual void Out_CameraPublishToWeb(DataInterceptedEventArgs e) { }
        public virtual void Out_BuyRoomPromotion(DataInterceptedEventArgs e) { }
        public virtual void Out_BuyItem(DataInterceptedEventArgs e) { }
        public virtual void Out_BreedPets(DataInterceptedEventArgs e) { }
        public virtual void Out_BotSettings(DataInterceptedEventArgs e) { }
        public virtual void Out_BotSaveSettings(DataInterceptedEventArgs e) { }
        public virtual void Out_BotPlace(DataInterceptedEventArgs e) { }
        public virtual void Out_CameraPurchase(DataInterceptedEventArgs e) { }
        public virtual void Out_BotPickup(DataInterceptedEventArgs e) { }
        public virtual void Out_AmbassadorVisitCommand(DataInterceptedEventArgs e) { }
        public virtual void Out_AmbassadorAlertCommand(DataInterceptedEventArgs e) { }
        public virtual void Out_AdvertisingSave(DataInterceptedEventArgs e) { }
        public virtual void Out_AdventCalendarOpenDay(DataInterceptedEventArgs e) { }
        public virtual void Out_AdventCalendarForceOpen(DataInterceptedEventArgs e) { }
        public virtual void Out_ActivateEffect(DataInterceptedEventArgs e) { }
        public virtual void Out_AcceptFriendRequest(DataInterceptedEventArgs e) { }
        public virtual void Out_AnswerPoll(DataInterceptedEventArgs e) { }
        public virtual void Out_FloorPlanEditorRequestBlockedTiles(DataInterceptedEventArgs e) { }
        public virtual void Out_CameraRoomPicture(DataInterceptedEventArgs e) { }
        public virtual void Out_CancelPoll(DataInterceptedEventArgs e) { }
        public virtual void Out_EnableEffect(DataInterceptedEventArgs e) { }
        public virtual void Out_EditRoomPromotionMessage(DataInterceptedEventArgs e) { }
        public virtual void Out_DeclineFriendRequest(DataInterceptedEventArgs e) { }
        public virtual void Out_CraftingCraftSecret(DataInterceptedEventArgs e) { }
        public virtual void Out_CraftingCraftItem(DataInterceptedEventArgs e) { }
        public virtual void Out_CraftingAddRecipe(DataInterceptedEventArgs e) { }
        public virtual void Out_ConfirmChangeName(DataInterceptedEventArgs e) { }
        public virtual void Out_CameraRoomThumbnail(DataInterceptedEventArgs e) { }
        public virtual void Out_CompostMonsterplant(DataInterceptedEventArgs e) { }
        public virtual void Out_ClientVariables(DataInterceptedEventArgs e) { }
        public virtual void Out_CheckPetName(DataInterceptedEventArgs e) { }
        public virtual void Out_ChangeRelation(DataInterceptedEventArgs e) { }
        public virtual void Out_ChangeNameCheckUsername(DataInterceptedEventArgs e) { }
        public virtual void Out_CatalogSearchedItem(DataInterceptedEventArgs e) { }
        public virtual void Out_CatalogBuyItemAsGift(DataInterceptedEventArgs e) { }
        public virtual void Out_CatalogBuyItem(DataInterceptedEventArgs e) { }
        public virtual void Out_CloseDice(DataInterceptedEventArgs e) { }
        public virtual void Out_YoutubeRequestPlayList(DataInterceptedEventArgs e) { }
        public virtual void Out_GuildSetFavorite(DataInterceptedEventArgs e) { }
        public virtual void Out_HorseRide(DataInterceptedEventArgs e) { }
        public virtual void Out_PetPackageName(DataInterceptedEventArgs e) { }
        public virtual void Out_OpenRecycleBox(DataInterceptedEventArgs e) { }
        public virtual void Out_NewNavigatorAction(DataInterceptedEventArgs e) { }
        public virtual void Out_NavigatorUncollapseCategory(DataInterceptedEventArgs e) { }
        public virtual void Out_NavigatorCollapseCategory(DataInterceptedEventArgs e) { }
        public virtual void Out_NavigatorCategoryListMode(DataInterceptedEventArgs e) { }
        public virtual void Out_MoveWallItem(DataInterceptedEventArgs e) { }
        public virtual void Out_PetPickup(DataInterceptedEventArgs e) { }
        public virtual void Out_MovePet(DataInterceptedEventArgs e) { }
        public virtual void Out_MoodLightSettings(DataInterceptedEventArgs e) { }
        public virtual void Out_MoodLightSaveSettings(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolWarn(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolSanctionTradeLock(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolSanctionMute(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolSanctionBan(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolSanctionAlert(DataInterceptedEventArgs e) { }
        public virtual void Out_MoodLightTurnOn(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolRoomAlert(DataInterceptedEventArgs e) { }
        public virtual void Out_PetPlace(DataInterceptedEventArgs e) { }
        public virtual void Out_Pong(DataInterceptedEventArgs e) { }
        public virtual void Out_RequestAchievementConfiguration(DataInterceptedEventArgs e) { }
        public virtual void Out_ReportBully(DataInterceptedEventArgs e) { }
        public virtual void Out_Report(DataInterceptedEventArgs e) { }
        public virtual void Out_RentSpaceCancel(DataInterceptedEventArgs e) { }
        public virtual void Out_RentSpace(DataInterceptedEventArgs e) { }
        public virtual void Out_RemoveFriend(DataInterceptedEventArgs e) { }
        public virtual void Out_ReloadRecycler(DataInterceptedEventArgs e) { }
        public virtual void Out_PickNewUserGift(DataInterceptedEventArgs e) { }
        public virtual void Out_ReleaseVersion(DataInterceptedEventArgs e) { }
        public virtual void Out_RedeemItem(DataInterceptedEventArgs e) { }
        public virtual void Out_RedeemClothing(DataInterceptedEventArgs e) { }
        public virtual void Out_Recycle(DataInterceptedEventArgs e) { }
        public virtual void Out_PostItSaveData(DataInterceptedEventArgs e) { }
        public virtual void Out_PostItRequestData(DataInterceptedEventArgs e) { }
        public virtual void Out_PostItPlace(DataInterceptedEventArgs e) { }
        public virtual void Out_PostItDelete(DataInterceptedEventArgs e) { }
        public virtual void Out_RedeemVoucher(DataInterceptedEventArgs e) { }
        public virtual void Out_HandleDoorbell(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolRequestUserInfo(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolRequestRoomVisits(DataInterceptedEventArgs e) { }
        public virtual void Out_JukeBoxEventOne(DataInterceptedEventArgs e) { }
        public virtual void Out_JukeBoxAddSoundTrack(DataInterceptedEventArgs e) { }
        public virtual void Out_InviteFriends(DataInterceptedEventArgs e) { }
        public virtual void Out_InitCrypto(DataInterceptedEventArgs e) { }
        public virtual void Out_IgnoreRoomUser(DataInterceptedEventArgs e) { }
        public virtual void Out_HotelViewRequestConcurrentUsers(DataInterceptedEventArgs e) { }
        public virtual void Out_HotelViewRequestCommunityGoal(DataInterceptedEventArgs e) { }
        public virtual void Out_JukeBoxEventThree(DataInterceptedEventArgs e) { }
        public virtual void Out_HotelViewRequestBonusRare(DataInterceptedEventArgs e) { }
        public virtual void Out_HotelViewData(DataInterceptedEventArgs e) { }
        public virtual void Out_HotelViewConcurrentUsersButton(DataInterceptedEventArgs e) { }
        public virtual void Out_HotelViewClaimBadgeReward(DataInterceptedEventArgs e) { }
        public virtual void Out_HotelViewClaimBadge(DataInterceptedEventArgs e) { }
        public virtual void Out_HotelView(DataInterceptedEventArgs e) { }
        public virtual void Out_HorseUseItem(DataInterceptedEventArgs e) { }
        public virtual void Out_HorseRideSettings(DataInterceptedEventArgs e) { }
        public virtual void Out_HotelViewRequestBadgeReward(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolRequestUserChatlog(DataInterceptedEventArgs e) { }
        public virtual void Out_JukeBoxEventTwo(DataInterceptedEventArgs e) { }
        public virtual void Out_JukeBoxRequestTrackCode(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolRequestRoomUserChatlog(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolRequestRoomInfo(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolRequestRoomChatlog(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolRequestIssueChatlog(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolReleaseTicket(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolPickTicket(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolKick(DataInterceptedEventArgs e) { }
        public virtual void Out_JukeBoxRequestPlayList(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolCloseTicket(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolBan(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolAlert(DataInterceptedEventArgs e) { }
        public virtual void Out_MannequinSaveName(DataInterceptedEventArgs e) { }
        public virtual void Out_MannequinSaveLook(DataInterceptedEventArgs e) { }
        public virtual void Out_MachineID(DataInterceptedEventArgs e) { }
        public virtual void Out_LatencyTest(DataInterceptedEventArgs e) { }
        public virtual void Out_JukeBoxRequestTrackData(DataInterceptedEventArgs e) { }
        public virtual void Out_ModToolChangeRoomSettings(DataInterceptedEventArgs e) { }
        public virtual void Out_YoutubeRequestVideoData(DataInterceptedEventArgs e) { }

        //Incoming events shared by multiple pages
        public virtual void In_RemoveHabboItem(DataInterceptedEventArgs e) { }
        public virtual void In_RemoveGuildFromRoom(DataInterceptedEventArgs e) { }
        public virtual void In_RemoveFriend(DataInterceptedEventArgs e) { }
        public virtual void In_RemoveHFloorObject(DataInterceptedEventArgs e) { }
        public virtual void In_RemoveBot(DataInterceptedEventArgs e) { }
        public virtual void In_ReloadRecycler(DataInterceptedEventArgs e) { }
        public virtual void In_RedeemVoucherOK(DataInterceptedEventArgs e) { }
        public virtual void In_RedeemVoucherError(DataInterceptedEventArgs e) { }
        public virtual void In_RecyclerLogic(DataInterceptedEventArgs e) { }
        public virtual void In_RecyclerComplete(DataInterceptedEventArgs e) { }
        public virtual void In_ReceivePrivateMessage(DataInterceptedEventArgs e) { }
        public virtual void In_ReceiveInvitation(DataInterceptedEventArgs e) { }
        public virtual void In_QuestExpired(DataInterceptedEventArgs e) { }
        public virtual void In_QuestCompleted(DataInterceptedEventArgs e) { }
        public virtual void In_PurchaseOK(DataInterceptedEventArgs e) { }
        public virtual void In_PublicRooms(DataInterceptedEventArgs e) { }
        public virtual void In_PromoteOwnRoomsList(DataInterceptedEventArgs e) { }
        public virtual void In_ProfileFriends(DataInterceptedEventArgs e) { }
        public virtual void In_PrivateMessageAlert(DataInterceptedEventArgs e) { }
        public virtual void In_PrivateRooms(DataInterceptedEventArgs e) { }
        public virtual void In_PresentItemOpened(DataInterceptedEventArgs e) { }
        public virtual void In_RemovePet(DataInterceptedEventArgs e) { }
        public virtual void In_RemoveRoomEvent(DataInterceptedEventArgs e) { }
        public virtual void In_RemoveWallItem(DataInterceptedEventArgs e) { }
        public virtual void In_RentableItemBuyOutPrice(DataInterceptedEventArgs e) { }
        public virtual void In_RoomMessagesPostedCount(DataInterceptedEventArgs e) { }
        public virtual void In_RoomInviteError(DataInterceptedEventArgs e) { }
        public virtual void In_RoomInvite(DataInterceptedEventArgs e) { }
        public virtual void In_RoomHeightMap(DataInterceptedEventArgs e) { }
        public virtual void In_RoomFloorThicknessUpdated(DataInterceptedEventArgs e) { }
        public virtual void In_RoomHFloorObjects(DataInterceptedEventArgs e) { }
        public virtual void In_RoomFilterWords(DataInterceptedEventArgs e) { }
        public virtual void In_RoomEventMessage(DataInterceptedEventArgs e) { }
        public virtual void In_RoomEntryInfo(DataInterceptedEventArgs e) { }
        public virtual void In_RoomEnterError(DataInterceptedEventArgs e) { }
        public virtual void In_PostItStickyPoleOpen(DataInterceptedEventArgs e) { }
        public virtual void In_RoomEditSettingsError(DataInterceptedEventArgs e) { }
        public virtual void In_RoomCreated(DataInterceptedEventArgs e) { }
        public virtual void In_RoomChatSettings(DataInterceptedEventArgs e) { }
        public virtual void In_RoomCategoryUpdateMessage(DataInterceptedEventArgs e) { }
        public virtual void In_RoomCategories(DataInterceptedEventArgs e) { }
        public virtual void In_RoomBannedUsers(DataInterceptedEventArgs e) { }
        public virtual void In_RoomAddRightsList(DataInterceptedEventArgs e) { }
        public virtual void In_RoomAdError(DataInterceptedEventArgs e) { }
        public virtual void In_RoomAccessDenied(DataInterceptedEventArgs e) { }
        public virtual void In_ReportRoomForm(DataInterceptedEventArgs e) { }
        public virtual void In_RentableSpaceInfo(DataInterceptedEventArgs e) { }
        public virtual void In_RoomData(DataInterceptedEventArgs e) { }
        public virtual void In_PostItData(DataInterceptedEventArgs e) { }
        public virtual void In_PollStart(DataInterceptedEventArgs e) { }
        public virtual void In_PollQuestions(DataInterceptedEventArgs e) { }
        public virtual void In_NewYearResolution(DataInterceptedEventArgs e) { }
        public virtual void In_NewUserIdentity(DataInterceptedEventArgs e) { }
        public virtual void In_NewUserGift(DataInterceptedEventArgs e) { }
        public virtual void In_NewNavigatorSettings(DataInterceptedEventArgs e) { }
        public virtual void In_NewNavigatorSearchResults(DataInterceptedEventArgs e) { }
        public virtual void In_NewNavigatorSavedSearches(DataInterceptedEventArgs e) { }
        public virtual void In_NewNavigatorRoomEvent(DataInterceptedEventArgs e) { }
        public virtual void In_NewNavigatorMetaData(DataInterceptedEventArgs e) { }
        public virtual void In_NewNavigatorLiftedRooms(DataInterceptedEventArgs e) { }
        public virtual void In_NewNavigatorEventCategories(DataInterceptedEventArgs e) { }
        public virtual void In_NewNavigatorCollapsedCategories(DataInterceptedEventArgs e) { }
        public virtual void In_NewNavigatorCategoryUserCount(DataInterceptedEventArgs e) { }
        public virtual void In_MysticBoxStartOpen(DataInterceptedEventArgs e) { }
        public virtual void In_MysticBoxPrize(DataInterceptedEventArgs e) { }
        public virtual void In_MysticBoxClose(DataInterceptedEventArgs e) { }
        public virtual void In_MutedWhisper(DataInterceptedEventArgs e) { }
        public virtual void In_MoodLightData(DataInterceptedEventArgs e) { }
        public virtual void In_ModToolUserRoomVisits(DataInterceptedEventArgs e) { }
        public virtual void In_ModToolUserInfo(DataInterceptedEventArgs e) { }
        public virtual void In_ModToolUserChatlog(DataInterceptedEventArgs e) { }
        public virtual void In_ModToolSanctionInfo(DataInterceptedEventArgs e) { }
        public virtual void In_NewYearResolutionCompleted(DataInterceptedEventArgs e) { }
        public virtual void In_NewYearResolutionProgress(DataInterceptedEventArgs e) { }
        public virtual void In_NewsWidgets(DataInterceptedEventArgs e) { }
        public virtual void In_NotEnoughPointsType(DataInterceptedEventArgs e) { }
        public virtual void In_Ping(DataInterceptedEventArgs e) { }
        public virtual void In_PickMonthlyClubGiftNotification(DataInterceptedEventArgs e) { }
        public virtual void In_PetTrainingPanel(DataInterceptedEventArgs e) { }
        public virtual void In_PetStatusUpdate(DataInterceptedEventArgs e) { }
        public virtual void In_PetPackageNameValidation(DataInterceptedEventArgs e) { }
        public virtual void In_PetNameError(DataInterceptedEventArgs e) { }
        public virtual void In_PetLevelUpdated(DataInterceptedEventArgs e) { }
        public virtual void In_PetLevelUp(DataInterceptedEventArgs e) { }
        public virtual void In_PetInfo(DataInterceptedEventArgs e) { }
        public virtual void In_PetError(DataInterceptedEventArgs e) { }
        public virtual void In_RoomModel(DataInterceptedEventArgs e) { }
        public virtual void In_PetBreeds(DataInterceptedEventArgs e) { }
        public virtual void In_PetBreedingStart(DataInterceptedEventArgs e) { }
        public virtual void In_PetBreedingResult(DataInterceptedEventArgs e) { }
        public virtual void In_PetBreedingFailed(DataInterceptedEventArgs e) { }
        public virtual void In_PetBreedingCompleted(DataInterceptedEventArgs e) { }
        public virtual void In_PetBoughtNotification(DataInterceptedEventArgs e) { }
        public virtual void In_OtherTradingDisabled(DataInterceptedEventArgs e) { }
        public virtual void In_OpenRoomCreationWindow(DataInterceptedEventArgs e) { }
        public virtual void In_OldPublicRooms(DataInterceptedEventArgs e) { }
        public virtual void In_ObjectOnRoller(DataInterceptedEventArgs e) { }
        public virtual void In_NuxAlert(DataInterceptedEventArgs e) { }
        public virtual void In_PetBreedingStartFailed(DataInterceptedEventArgs e) { }
        public virtual void In_RoomMuted(DataInterceptedEventArgs e) { }
        public virtual void In_RoomNoRights(DataInterceptedEventArgs e) { }
        public virtual void In_RoomOpen(DataInterceptedEventArgs e) { }
        public virtual void In_UserCurrency(DataInterceptedEventArgs e) { }
        public virtual void In_UserCredits(DataInterceptedEventArgs e) { }
        public virtual void In_UserClub(DataInterceptedEventArgs e) { }
        public virtual void In_UserClothes(DataInterceptedEventArgs e) { }
        public virtual void In_UserCitizinShip(DataInterceptedEventArgs e) { }
        public virtual void In_UserBadges(DataInterceptedEventArgs e) { }
        public virtual void In_UserAchievementScore(DataInterceptedEventArgs e) { }
        public virtual void In_UpdateUserLook(DataInterceptedEventArgs e) { }
        public virtual void In_UpdateStackHeightTileHeight(DataInterceptedEventArgs e) { }
        public virtual void In_UpdateStackHeight(DataInterceptedEventArgs e) { }
        public virtual void In_UpdateFriend(DataInterceptedEventArgs e) { }
        public virtual void In_UpdateFailed(DataInterceptedEventArgs e) { }
        public virtual void In_TradingWaitingConfirm(DataInterceptedEventArgs e) { }
        public virtual void In_TradeUpdate(DataInterceptedEventArgs e) { }
        public virtual void In_TradeStopped(DataInterceptedEventArgs e) { }
        public virtual void In_TradeStartFail(DataInterceptedEventArgs e) { }
        public virtual void In_TradeStart(DataInterceptedEventArgs e) { }
        public virtual void In_TradeComplete(DataInterceptedEventArgs e) { }
        public virtual void In_TradeCloseWindow(DataInterceptedEventArgs e) { }
        public virtual void In_TradeAccepted(DataInterceptedEventArgs e) { }
        public virtual void In_TargetedOffer(DataInterceptedEventArgs e) { }
        public virtual void In_UserData(DataInterceptedEventArgs e) { }
        public virtual void In_UserEffectsList(DataInterceptedEventArgs e) { }
        public virtual void In_UserHomeRoom(DataInterceptedEventArgs e) { }
        public virtual void In_UserPerks(DataInterceptedEventArgs e) { }
        public virtual void In_YoutubeDisplayList(DataInterceptedEventArgs e) { }
        public virtual void In_YouTradingDisabled(DataInterceptedEventArgs e) { }
        public virtual void In_WiredTriggerData(DataInterceptedEventArgs e) { }
        public virtual void In_WiredSaved(DataInterceptedEventArgs e) { }
        public virtual void In_WiredRewardAlert(DataInterceptedEventArgs e) { }
        public virtual void In_WiredEffectData(DataInterceptedEventArgs e) { }
        public virtual void In_WiredConditionData(DataInterceptedEventArgs e) { }
        public virtual void In_WelcomeGiftError(DataInterceptedEventArgs e) { }
        public virtual void In_WelcomeGift(DataInterceptedEventArgs e) { }
        public virtual void In_WatchAndEarnReward(DataInterceptedEventArgs e) { }
        public virtual void In_TalentTrackEmailVerified(DataInterceptedEventArgs e) { }
        public virtual void In_WallItemUpdate(DataInterceptedEventArgs e) { }
        public virtual void In_VerifyPrimes(DataInterceptedEventArgs e) { }
        public virtual void In_VerifyMobilePhoneWindow(DataInterceptedEventArgs e) { }
        public virtual void In_VerifyMobilePhoneDone(DataInterceptedEventArgs e) { }
        public virtual void In_VerifyMobilePhoneCodeWindow(DataInterceptedEventArgs e) { }
        public virtual void In_VerifyMobileNumber(DataInterceptedEventArgs e) { }
        public virtual void In_UserWardrobe(DataInterceptedEventArgs e) { }
        public virtual void In_UserSearchResult(DataInterceptedEventArgs e) { }
        public virtual void In_UserProfile(DataInterceptedEventArgs e) { }
        public virtual void In_UserPoints(DataInterceptedEventArgs e) { }
        public virtual void In_UserPermissions(DataInterceptedEventArgs e) { }
        public virtual void In_VipTutorialsStart(DataInterceptedEventArgs e) { }
        public virtual void In_ModToolSanctionData(DataInterceptedEventArgs e) { }
        public virtual void In_TalentTrackEmailFailed(DataInterceptedEventArgs e) { }
        public virtual void In_TalentLevelUpdate(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserIgnored(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserHandItem(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserEffect(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserData(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserDance(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserAction(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUnitIdle(DataInterceptedEventArgs e) { }
        public virtual void In_RoomThickness(DataInterceptedEventArgs e) { }
        public virtual void In_RoomSettingsUpdated(DataInterceptedEventArgs e) { }
        public virtual void In_RoomSettingsSaved(DataInterceptedEventArgs e) { }
        public virtual void In_RoomSettings(DataInterceptedEventArgs e) { }
        public virtual void In_RoomScore(DataInterceptedEventArgs e) { }
        public virtual void In_RoomRightsList(DataInterceptedEventArgs e) { }
        public virtual void In_RoomRights(DataInterceptedEventArgs e) { }
        public virtual void In_RoomRemoveRightsList(DataInterceptedEventArgs e) { }
        public virtual void In_RoomRelativeMap(DataInterceptedEventArgs e) { }
        public virtual void In_RoomPetRespect(DataInterceptedEventArgs e) { }
        public virtual void In_RoomPetHorseFigure(DataInterceptedEventArgs e) { }
        public virtual void In_RoomPetExperience(DataInterceptedEventArgs e) { }
        public virtual void In_RoomPaint(DataInterceptedEventArgs e) { }
        public virtual void In_RoomOwner(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserNameChanged(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserReceivedHandItem(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserRemove(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserRemoveRights(DataInterceptedEventArgs e) { }
        public virtual void In_Tags(DataInterceptedEventArgs e) { }
        public virtual void In_SubmitCompetitionRoom(DataInterceptedEventArgs e) { }
        public virtual void In_StalkError(DataInterceptedEventArgs e) { }
        public virtual void In_StaffAlertWithLink(DataInterceptedEventArgs e) { }
        public virtual void In_StaffAlertWIthLinkAndOpenHabboWay(DataInterceptedEventArgs e) { }
        public virtual void In_StaffAlertAndOpenHabboWay(DataInterceptedEventArgs e) { }
        public virtual void In_SimplePollStart(DataInterceptedEventArgs e) { }
        public virtual void In_SimplePollAnswers(DataInterceptedEventArgs e) { }
        public virtual void In_SimplePollAnswer(DataInterceptedEventArgs e) { }
        public virtual void In_SessionRights(DataInterceptedEventArgs e) { }
        public virtual void In_TalentTrack(DataInterceptedEventArgs e) { }
        public virtual void In_SecureLoginOK(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUsersGuildBadges(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUsers(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserWhisper(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserUnbanned(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserTyping(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserTalk(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserTags(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserStatus(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserShout(DataInterceptedEventArgs e) { }
        public virtual void In_RoomUserRespect(DataInterceptedEventArgs e) { }
        public virtual void In_RoomWallItems(DataInterceptedEventArgs e) { }
        public virtual void In_ModToolRoomInfo(DataInterceptedEventArgs e) { }
        public virtual void In_ModToolRoomChatlog(DataInterceptedEventArgs e) { }
        public virtual void In_ModToolReportReceivedAlert(DataInterceptedEventArgs e) { }
        public virtual void In_FloorPlanEditorBlockedTiles(DataInterceptedEventArgs e) { }
        public virtual void In_HFloorObjectUpdate(DataInterceptedEventArgs e) { }
        public virtual void In_FloodCounter(DataInterceptedEventArgs e) { }
        public virtual void In_FavoriteRoomsCount(DataInterceptedEventArgs e) { }
        public virtual void In_FavoriteRoomChanged(DataInterceptedEventArgs e) { }
        public virtual void In_ExtendClubMessage(DataInterceptedEventArgs e) { }
        public virtual void In_ErrorLogin(DataInterceptedEventArgs e) { }
        public virtual void In_EpicPopupFrame(DataInterceptedEventArgs e) { }
        public virtual void In_EffectsListRemove(DataInterceptedEventArgs e) { }
        public virtual void In_EffectsListEffectEnable(DataInterceptedEventArgs e) { }
        public virtual void In_EffectsListAdd(DataInterceptedEventArgs e) { }
        public virtual void In_DoorbellAddUser(DataInterceptedEventArgs e) { }
        public virtual void In_Discount(DataInterceptedEventArgs e) { }
        public virtual void In_DebugConsole(DataInterceptedEventArgs e) { }
        public virtual void In_DailyQuest(DataInterceptedEventArgs e) { }
        public virtual void In_CustomNotification(DataInterceptedEventArgs e) { }
        public virtual void In_CraftingResult(DataInterceptedEventArgs e) { }
        public virtual void In_CraftingRecipe(DataInterceptedEventArgs e) { }
        public virtual void In_CraftingComposerFour(DataInterceptedEventArgs e) { }
        public virtual void In_CraftableProducts(DataInterceptedEventArgs e) { }
        public virtual void In_ConvertedForwardToRoom(DataInterceptedEventArgs e) { }
        public virtual void In_FloorPlanEditorDoorSettings(DataInterceptedEventArgs e) { }
        public virtual void In_ForwardToRoom(DataInterceptedEventArgs e) { }
        public virtual void In_FreezeLives(DataInterceptedEventArgs e) { }
        public virtual void In_FriendChatMessage(DataInterceptedEventArgs e) { }
        public virtual void In_GuardianVotingTimeEnded(DataInterceptedEventArgs e) { }
        public virtual void In_GuardianVotingResult(DataInterceptedEventArgs e) { }
        public virtual void In_GuardianVotingRequested(DataInterceptedEventArgs e) { }
        public virtual void In_GuardianNewReportReceived(DataInterceptedEventArgs e) { }
        public virtual void In_GroupParts(DataInterceptedEventArgs e) { }
        public virtual void In_GiftReceiverNotFound(DataInterceptedEventArgs e) { }
        public virtual void In_GiftConfiguration(DataInterceptedEventArgs e) { }
        public virtual void In_GenericErrorMessages(DataInterceptedEventArgs e) { }
        public virtual void In_GenericAlert(DataInterceptedEventArgs e) { }
        public virtual void In_GenerateSecretKey(DataInterceptedEventArgs e) { }
        public virtual void In_ConnectionError(DataInterceptedEventArgs e) { }
        public virtual void In_GameCenterGameList(DataInterceptedEventArgs e) { }
        public virtual void In_GameCenterFeaturedPlayers(DataInterceptedEventArgs e) { }
        public virtual void In_GameCenterAccountInfo(DataInterceptedEventArgs e) { }
        public virtual void In_GameAchievementsList(DataInterceptedEventArgs e) { }
        public virtual void In_Game2WeeklySmallLeaderboard(DataInterceptedEventArgs e) { }
        public virtual void In_Game2WeeklyLeaderboard(DataInterceptedEventArgs e) { }
        public virtual void In_Friends(DataInterceptedEventArgs e) { }
        public virtual void In_FriendToolbarNotification(DataInterceptedEventArgs e) { }
        public virtual void In_FriendRequestError(DataInterceptedEventArgs e) { }
        public virtual void In_FriendRequest(DataInterceptedEventArgs e) { }
        public virtual void In_FriendFindingRoom(DataInterceptedEventArgs e) { }
        public virtual void In_GameCenterGame(DataInterceptedEventArgs e) { }
        public virtual void In_GuardianVotingVotes(DataInterceptedEventArgs e) { }
        public virtual void In_CompetitionEntrySubmitResult(DataInterceptedEventArgs e) { }
        public virtual void In_ClubGiftReceived(DataInterceptedEventArgs e) { }
        public virtual void In_BonusRare(DataInterceptedEventArgs e) { }
        public virtual void In_BaseJumpUnloadGame(DataInterceptedEventArgs e) { }
        public virtual void In_BaseJumpLoadGameURL(DataInterceptedEventArgs e) { }
        public virtual void In_BaseJumpLoadGame(DataInterceptedEventArgs e) { }
        public virtual void In_BaseJumpLeaveQueue(DataInterceptedEventArgs e) { }
        public virtual void In_BaseJumpJoinQueue(DataInterceptedEventArgs e) { }
        public virtual void In_AlertPurchaseUnavailable(DataInterceptedEventArgs e) { }
        public virtual void In_AlertPurchaseFailed(DataInterceptedEventArgs e) { }
        public virtual void In_AlertLimitedSoldOut(DataInterceptedEventArgs e) { }
        public virtual void In_AdventCalendarProduct(DataInterceptedEventArgs e) { }
        public virtual void In_AdventCalendarData(DataInterceptedEventArgs e) { }
        public virtual void In_AddWallItem(DataInterceptedEventArgs e) { }
        public virtual void In_AddUserBadge(DataInterceptedEventArgs e) { }
        public virtual void In_AddPet(DataInterceptedEventArgs e) { }
        public virtual void In_AddHabboItem(DataInterceptedEventArgs e) { }
        public virtual void In_AddHFloorObject(DataInterceptedEventArgs e) { }
        public virtual void In_AddBot(DataInterceptedEventArgs e) { }
        public virtual void In_AchievementsConfiguration(DataInterceptedEventArgs e) { }
        public virtual void In_AchievementUnlocked(DataInterceptedEventArgs e) { }
        public virtual void In_AchievementProgress(DataInterceptedEventArgs e) { }
        public virtual void In_AchievementList(DataInterceptedEventArgs e) { }
        public virtual void In_BotError(DataInterceptedEventArgs e) { }
        public virtual void In_BotSettings(DataInterceptedEventArgs e) { }
        public virtual void In_BubbleAlert(DataInterceptedEventArgs e) { }
        public virtual void In_BuildersClubExpired(DataInterceptedEventArgs e) { }
        public virtual void In_ClubData(DataInterceptedEventArgs e) { }
        public virtual void In_ClubCenterData(DataInterceptedEventArgs e) { }
        public virtual void In_CloseWebPage(DataInterceptedEventArgs e) { }
        public virtual void In_ChangeNameUpdate(DataInterceptedEventArgs e) { }
        public virtual void In_CfhTopicsMessage(DataInterceptedEventArgs e) { }
        public virtual void In_CatalogUpdated(DataInterceptedEventArgs e) { }
        public virtual void In_CatalogSearchResult(DataInterceptedEventArgs e) { }
        public virtual void In_CatalogPagesList(DataInterceptedEventArgs e) { }
        public virtual void In_CatalogPage(DataInterceptedEventArgs e) { }
        public virtual void In_CatalogMode(DataInterceptedEventArgs e) { }
        public virtual void In_ClubGifts(DataInterceptedEventArgs e) { }
        public virtual void In_CantScratchPetNotOldEnough(DataInterceptedEventArgs e) { }
        public virtual void In_CanCreateEvent(DataInterceptedEventArgs e) { }
        public virtual void In_CameraURL(DataInterceptedEventArgs e) { }
        public virtual void In_CameraRoomThumbnailSaved(DataInterceptedEventArgs e) { }
        public virtual void In_CameraPurchaseSuccesfull(DataInterceptedEventArgs e) { }
        public virtual void In_CameraPublishWaitMessage(DataInterceptedEventArgs e) { }
        public virtual void In_CameraPrice(DataInterceptedEventArgs e) { }
        public virtual void In_CameraCompetitionStatus(DataInterceptedEventArgs e) { }
        public virtual void In_BullyReportedMessage(DataInterceptedEventArgs e) { }
        public virtual void In_BullyReportRequest(DataInterceptedEventArgs e) { }
        public virtual void In_BullyReportClosed(DataInterceptedEventArgs e) { }
        public virtual void In_CanCreateRoom(DataInterceptedEventArgs e) { }
        public virtual void In_GuideSessionAttached(DataInterceptedEventArgs e) { }
        public virtual void In_GuideSessionDetached(DataInterceptedEventArgs e) { }
        public virtual void In_GuideSessionEnded(DataInterceptedEventArgs e) { }
        public virtual void In_LoveLockFurniFinished(DataInterceptedEventArgs e) { }
        public virtual void In_LoadFriendRequests(DataInterceptedEventArgs e) { }
        public virtual void In_LeprechaunStarterBundle(DataInterceptedEventArgs e) { }
        public virtual void In_LatencyResponse(DataInterceptedEventArgs e) { }
        public virtual void In_JukeBoxTrackData(DataInterceptedEventArgs e) { }
        public virtual void In_JukeBoxTrackCode(DataInterceptedEventArgs e) { }
        public virtual void In_JukeBoxPlaylistFull(DataInterceptedEventArgs e) { }
        public virtual void In_JukeBoxPlayListUpdated(DataInterceptedEventArgs e) { }
        public virtual void In_JukeBoxPlayListAddSong(DataInterceptedEventArgs e) { }
        public virtual void In_JukeBoxPlayList(DataInterceptedEventArgs e) { }
        public virtual void In_JukeBoxNowPlayingMessage(DataInterceptedEventArgs e) { }
        public virtual void In_JukeBoxMySongs(DataInterceptedEventArgs e) { }
        public virtual void In_ItemsDataUpdate(DataInterceptedEventArgs e) { }
        public virtual void In_ItemStateComposer2(DataInterceptedEventArgs e) { }
        public virtual void In_ItemState(DataInterceptedEventArgs e) { }
        public virtual void In_ItemExtraData(DataInterceptedEventArgs e) { }
        public virtual void In_InventoryRefresh(DataInterceptedEventArgs e) { }
        public virtual void In_InventoryPets(DataInterceptedEventArgs e) { }
        public virtual void In_InventoryItems(DataInterceptedEventArgs e) { }
        public virtual void In_InventoryItemUpdate(DataInterceptedEventArgs e) { }
        public virtual void In_InventoryBots(DataInterceptedEventArgs e) { }
        public virtual void In_LoveLockFurniFriendConfirmed(DataInterceptedEventArgs e) { }
        public virtual void In_LoveLockFurniStart(DataInterceptedEventArgs e) { }
        public virtual void In_MachineID(DataInterceptedEventArgs e) { }
        public virtual void In_MarketplaceBuyError(DataInterceptedEventArgs e) { }
        public virtual void In_ModToolIssueUpdate(DataInterceptedEventArgs e) { }
        public virtual void In_ModToolIssueResponseAlert(DataInterceptedEventArgs e) { }
        public virtual void In_ModToolIssueInfo(DataInterceptedEventArgs e) { }
        public virtual void In_ModToolIssueHandlerDimensions(DataInterceptedEventArgs e) { }
        public virtual void In_ModToolIssueHandled(DataInterceptedEventArgs e) { }
        public virtual void In_ModToolIssueChatlog(DataInterceptedEventArgs e) { }
        public virtual void In_ModToolComposerTwo(DataInterceptedEventArgs e) { }
        public virtual void In_ModToolComposerOne(DataInterceptedEventArgs e) { }
        public virtual void In_ModTool(DataInterceptedEventArgs e) { }
        public virtual void In_MinimailNewMessage(DataInterceptedEventArgs e) { }
        public virtual void In_InventoryBadges(DataInterceptedEventArgs e) { }
        public virtual void In_MinimailCount(DataInterceptedEventArgs e) { }
        public virtual void In_MessengerError(DataInterceptedEventArgs e) { }
        public virtual void In_MessagesForYou(DataInterceptedEventArgs e) { }
        public virtual void In_MeMenuSettings(DataInterceptedEventArgs e) { }
        public virtual void In_MarketplaceSellItem(DataInterceptedEventArgs e) { }
        public virtual void In_MarketplaceOwnItems(DataInterceptedEventArgs e) { }
        public virtual void In_MarketplaceOffers(DataInterceptedEventArgs e) { }
        public virtual void In_MarketplaceItemPosted(DataInterceptedEventArgs e) { }
        public virtual void In_MarketplaceItemInfo(DataInterceptedEventArgs e) { }
        public virtual void In_MarketplaceConfig(DataInterceptedEventArgs e) { }
        public virtual void In_MarketplaceCancelSale(DataInterceptedEventArgs e) { }
        public virtual void In_MessengerInit(DataInterceptedEventArgs e) { }
        public virtual void In_InventoryAddEffect(DataInterceptedEventArgs e) { }
        public virtual void In_InventoryAchievements(DataInterceptedEventArgs e) { }
        public virtual void In_HotelWillCloseInMinutesAndBackIn(DataInterceptedEventArgs e) { }
        public virtual void In_GuildFurniWidget(DataInterceptedEventArgs e) { }
        public virtual void In_GuildForumsUnreadMessagesCount(DataInterceptedEventArgs e) { }
        public virtual void In_GuildForumThreads(DataInterceptedEventArgs e) { }
        public virtual void In_GuildForumThreadMessages(DataInterceptedEventArgs e) { }
        public virtual void In_GuildForumList(DataInterceptedEventArgs e) { }
        public virtual void In_GuildForumData(DataInterceptedEventArgs e) { }
        public virtual void In_GuildForumComments(DataInterceptedEventArgs e) { }
        public virtual void In_GuildForumAddComment(DataInterceptedEventArgs e) { }
        public virtual void In_GuildFavoriteRoomUserUpdate(DataInterceptedEventArgs e) { }
        public virtual void In_GuildEditFail(DataInterceptedEventArgs e) { }
        public virtual void In_GuildInfo(DataInterceptedEventArgs e) { }
        public virtual void In_GuildConfirmRemoveMember(DataInterceptedEventArgs e) { }
        public virtual void In_GuildBought(DataInterceptedEventArgs e) { }
        public virtual void In_GuildAcceptMemberError(DataInterceptedEventArgs e) { }
        public virtual void In_GuideTools(DataInterceptedEventArgs e) { }
        public virtual void In_GuideSessionStarted(DataInterceptedEventArgs e) { }
        public virtual void In_GuideSessionRequesterRoom(DataInterceptedEventArgs e) { }
        public virtual void In_GuideSessionPartnerIsTyping(DataInterceptedEventArgs e) { }
        public virtual void In_GuideSessionPartnerIsPlaying(DataInterceptedEventArgs e) { }
        public virtual void In_GuideSessionMessage(DataInterceptedEventArgs e) { }
        public virtual void In_GuideSessionInvitedToGuideRoom(DataInterceptedEventArgs e) { }
        public virtual void In_GuideSessionError(DataInterceptedEventArgs e) { }
        public virtual void In_GuildBuyRooms(DataInterceptedEventArgs e) { }
        public virtual void In_YoutubeMessageComposer2(DataInterceptedEventArgs e) { }
        public virtual void In_GuildJoinError(DataInterceptedEventArgs e) { }
        public virtual void In_GuildManage(DataInterceptedEventArgs e) { }
        public virtual void In_HotelWillCloseInMinutes(DataInterceptedEventArgs e) { }
        public virtual void In_HotelViewNextLTDAvailable(DataInterceptedEventArgs e) { }
        public virtual void In_HotelViewHideCommunityVoteButton(DataInterceptedEventArgs e) { }
        public virtual void In_HotelViewExpiringCatalogPageCommposer(DataInterceptedEventArgs e) { }
        public virtual void In_HotelViewData(DataInterceptedEventArgs e) { }
        public virtual void In_HotelViewCustomTimer(DataInterceptedEventArgs e) { }
        public virtual void In_HotelViewConcurrentUsers(DataInterceptedEventArgs e) { }
        public virtual void In_HotelViewCommunityGoal(DataInterceptedEventArgs e) { }
        public virtual void In_HotelViewCatalogPageExpiring(DataInterceptedEventArgs e) { }
        public virtual void In_HotelViewBadgeButtonConfig(DataInterceptedEventArgs e) { }
        public virtual void In_GuildList(DataInterceptedEventArgs e) { }
        public virtual void In_HotelView(DataInterceptedEventArgs e) { }
        public virtual void In_HotelClosedAndOpens(DataInterceptedEventArgs e) { }
        public virtual void In_HideDoorbell(DataInterceptedEventArgs e) { }
        public virtual void In_HelperRequestDisabled(DataInterceptedEventArgs e) { }
        public virtual void In_HallOfFame(DataInterceptedEventArgs e) { }
        public virtual void In_HabboWayQuizComposer2(DataInterceptedEventArgs e) { }
        public virtual void In_HabboWayQuizComposer1(DataInterceptedEventArgs e) { }
        public virtual void In_HabboMall(DataInterceptedEventArgs e) { }
        public virtual void In_GuildRefreshMembersList(DataInterceptedEventArgs e) { }
        public virtual void In_GuildMembers(DataInterceptedEventArgs e) { }
        public virtual void In_GuildMemberUpdate(DataInterceptedEventArgs e) { }
        public virtual void In_HotelClosesAndWillOpenAt(DataInterceptedEventArgs e) { }
        public virtual void In_YoutubeMessageComposer3(DataInterceptedEventArgs e) { }
    }
}